apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: dock-reg-0001.ml/asset-app
    newTag: latest
configMapGenerator:
  - name: app-config
    behavior: replace
    literals:
      - MYSQL_HOST=mysql-service
      - MYSQL_PORT=3306
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
replicas:
  - name: appdeploy
    count: 3

## use a secrets generator
#secretGenerator:
#  - name: db-user-pass
#    files:
#      - username.txt
#      - password.txt

resources:
  - ../../manifests
  - mysql.yaml
  - mysql-secret.yaml
  - app-secret.yaml