apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: YXNzZXQtYXBwCg==
  MYSQL_PASSWORD: YWtqZ1NEZiM2OQo=
  MYSQL_DB: YXNzZXRfZGIK

# intended to use only in dev/staging