apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
  labels:
    app: asset-app
spec:
  selector:
    matchLabels:
      app: asset-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: asset-app
    spec:
      containers:
        - name: appdeploy
          image: dock-reg-0001.mlasset-app:0.1.4
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: regcred

