apiVersion: v1
kind: Service
metadata:
  name: appdeploy
  labels:
    app: asset-app
spec:
  ports:
    - port: 80
      protocol: TCP
      name: flask
  selector:
    app: asset-app
  type: LoadBalancer