apiVersion: v1
kind: Service
metadata:
  name: asset-service
  labels:
    app: asset-app
spec:
  ports:
    - port: 5000
      protocol: TCP
      name: flask
  selector:
    app: asset-app
  type: LoadBalancer