apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-asset
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
     - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: asset-service
                port:
                  number: 5000
  ingressClassName: nginx

#todo change app with real domain name