apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namesapce }}
  name: asset-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 5000
      port: 5000
  selector:
    app: asset-app
