apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namesapce }}
  name: appdeploy
  labels:
    app: asset-app
spec:
  selector:
    matchLabels:
      app: asset-app
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: asset-app
    spec:
      containers:
        - name: appdeploy
          image: {{ .Values.image.dockerRegistry }}/{{ .Values.image.nameTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: regcred

