apiVersion: v1
clusters:
  - cluster:
      certificate-authority: environments/staging/ca.crt
      extensions:
        - extension:
            last-update: Sun, 28 Nov 2021 14:54:40 UTC
            provider: minikube.sigs.k8s.io
            version: v1.24.0
          name: cluster_info
      server: 'https://{{ secrets.STAGING_IP }}:8443'
    name: minikube
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Sun, 28 Nov 2021 14:54:40 UTC
            provider: minikube.sigs.k8s.io
            version: v1.24.0
          name: context_info
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: environments/staging/client.crt
      client-key: client.key