apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: dock-reg-0001.ml/asset-app
    newTag: 0.1.26
configMapGenerator:
  - name: app-config
    behavior: replace
    literals:
      - MYSQL_HOST=34.82.186.182
      - MYSQL_PORT=7443
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
# TODO replace mysql host name

namespace: prod
resources:
  - ../../manifests
#  - cert.yaml
  - ingress-prod.yaml
