# Default values for production env.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  pullPolicy: Always
  dockerRegistry: dock-reg-0001.ml
  nameTag: asset-app:0.1.4


