# Default values for staging env.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  pullPolicy: Always
  dockerRegistry: dock-reg-0001.ml
  nameTag: asset-app:0.1.2



