apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: dock-reg-0001.ml/asset-app
    newTag: 1.1.5

resources:
  - asset-app-deployment.yaml
  - asset-app-ingress.yaml
  - asset-app-service.yaml
  - redis-configmap.yaml
  - redis-pod.yaml
  - redis-service.yaml